#!/usr/bin/env sh

case "$1" in
    lock)
        scrot /tmp/screenshot.png
        convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
        i3lock -i /tmp/screenshotblur.png
        
        #terminator -e cmtraix &
        #sleep 2
        #i3-msg fullscreen
        #i3lock -n; i3-msg kill
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
