# Polybar version: 3.7.1
# Ref: https://github.com/polybar/polybar/wiki

# Dependencies:
# pacman-contrib,
# pcmanfm,
# btop
# gsimplecal
# calcurse
# pavucontrol,
# Font Awesome 6 (Free)

[colors]
dracula = #6272a4
hacker = #23ea33
red = #bd2c40
dark = #050505
black = #000000
light = #fdfdfd
cyan = #00ffff
cianeto = #15ddc2
slack = #00a9a8
arch = #00aeff
purple = #baa1ff
primary = ${colors.light}
secondary = ${colors.black}
bar_border_bottom = ${colors.light}
workspace_select = ${colors.light}

[bar/mybar]
monitor = "HDMI-0"
enable-ipc = true
background = ${colors.secondary}
foreground = ${colors.primary}
width = 100%
height = 24
radius = 0
border-bottom-size = 1
border-color = ${colors.bar_border_bottom}
; tray-position = right
;tray-padding = 3
;tray-detached = true
;tray-offset-x = 12
;tray-offset-y = 0
;tray-transparent = true
;tray-foreground = ${colors.primary}
;tray-background = ${colors.secondary}
;override-redirect = true
fixed-center = true
;offset-y = 1px
;scroll-up = i3wm-wsnext
;scroll-down = i3wm-wsprev
scroll-up = i3-msg workspace next_on_output
scroll-down = i3-msg workspace prev_on_output
font-0 = "JetBrains Mono:size=10;1"
font-1 = "Font Awesome 6 Free:style=Solid:size=10;1"
font-2 = "Font Awesome 6 Brands:size=10;1"
modules-left = i3 separator xwindow
;modules-left = console browser manager-files editor message telegram i3
modules-center = calendar separator clock
modules-right = spotify separator btop separator memory separator update-system separator nightmode separator temperature separator-2 tray separator-2 xkeyboard separator pulseaudio separator wan separator
cursor-click = pointer
format-underline =
format-background =
format-padding =

[module/clock]
type = internal/date
;date = " %A, %d %B  %R"
date = " %R"

[module/calendar]
type = custom/script
exec = ~/.config/polybar/scripts/calendar.sh --calendar
interval = 3
click-left = ~/.config/polybar/scripts/calendar.sh --open

[module/tray]
type = internal/tray
tray-position = right
tray-spacing = 15px
format-margin = 7px

;[module/tray-spacer]
;type = custom/script
;exec = ~/.config/polybar/scripts/tray-spacer.sh --show
;tail = true

[module/separator]
type = custom/text
# 4 space default
format = "  "

[module/separator-2]
# 2 space default
type = custom/text
format = " "

[module/nightmode]
type = custom/script
exec = ~/.config/polybar/scripts/nightmode.sh --status
interval = 1
click-left = ~/.config/polybar/scripts/nightmode.sh --toggle

[module/btop]
type = custom/script
exec=~/.config/polybar/scripts/analytics.sh --show
click-left = ~/.config/polybar/scripts/analytics.sh --open

[module/pulseaudio-control]
type = custom/script
tail = true
label=%output%
;label-foreground = #FFFFFF
format-underline = #333333
exec = ~/.config/polybar/scripts/pulseaudio_control.bash listen
click-right =  ~/.config/polybar/scripts/pulseaudio_control.bash pavucontrol
click-left = ~/.config/polybar/scripts/pulseaudio_control.bash togmute
click-middle = ~/.config/polybar/scripts/pulseaudio_control.bash next-sink
scroll-up = ~/.config/polybar/scripts/pulseaudio_control.bash up
scroll-down = ~/.config/polybar/scripts/pulseaudio_control.bash down
label-padding = 2
;label-foreground = ${colors.foreground}

[module/xwindow]
type = internal/xwindow
label = "%title:0:30:...%"

[module/i3]
type = internal/i3
pin-workspaces = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = true
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true
format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 2
label-focused = %index%
label-focused-foreground = ${colors.secondary}
label-focused-background = ${colors.workspace_select}
label-focused-padding = 2
label-unfocused = %index%
label-unfocused-padding = 2
label-visible = %index%
label-visible-padding = 2
label-urgent = %index%
label-urgent-foreground = ${colors.secondary}
label-urgent-background = ${colors.red}
label-urgent-padding = 2

[module/temperature]
type = internal/temperature
interval = 0.5
thermal-zone = 0
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp1_input
base-temperature = 47
warn-temperature = 82
units = false
format = <ramp> <label>
format-warn = <label-warn>
format-padding = 0
label = %temperature-c%°C
label-warn = %temperature-c%°C
label-warn-foreground = #f00
format-warn-padding = 1
ramp-0 = 
ramp-1 = 
ramp-2 = 
; ramp-foreground = #ffffff

[module/wan]
type = custom/script
exec = ~/.config/polybar/scripts/network.sh --show
interval = 3
click-left = ~/.config/polybar/scripts/network.sh --vim

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout>
format-spacing = 0
label-layout = %icon%
label-layout-padding = 0
layout-icon-0 = br; br
layout-icon-1 = us; us
; click-left = "setxkbmap -layout us,br -option grp:alt_shift_toggle && xdotool key Alt+Shift_L"

[module/memory]
type = internal/memory
interval = 3
format = <label>
;format = <label> <bar-used>
;format = RAM <bar-used>
;label = RAM: %gb_used%/%gb_free%
; label =  %gb_free%
label =  %gb_used%
; label = RAM:
bar-used-indicator =
bar-used-width = 50
bar-used-foreground-0 = #55aa55
bar-used-foreground-1 = #557755
bar-used-foreground-2 = #f5a70a
bar-used-foreground-3 = #ff5555
bar-used-fill = ▐
bar-used-empty = ▐
bar-used-empty-foreground = #444444
ramp-used-0 = ▁
ramp-used-1 = ▂
ramp-used-2 = ▃
ramp-used-3 = ▄
ramp-used-4 = ▅
ramp-used-5 = ▆
ramp-used-6 = ▇
ramp-used-7 = █
ramp-free-0 = ▁
ramp-free-1 = ▂
ramp-free-2 = ▃
ramp-free-3 = ▄
ramp-free-4 = ▅
ramp-free-5 = ▆
ramp-free-6 = ▇
ramp-free-7 = █

[module/pulseaudio]
type = internal/pulseaudio
sink = alsa_output.pci-0000_00_1b.0.analog-stereo
use-ui-max = false
reverse-scroll = false
interval = 5
format-volume = <ramp-volume> <label-volume>
label-muted =  muted
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
click-right = pavucontrol &

[module/update-system]
type = custom/script
exec = ~/.config/polybar/scripts/update_system.sh --show
interval = 3
;label = %output%
;format-prefix = " "
click-left = ~/.config/polybar/scripts/update_system.sh --open-terminal

# Option 1:
[module/spotify]
type = custom/script
exec = echo "$(playerctl --player=spotify metadata --format ' [ {{ title }} - {{ artist }} ]' 2>/dev/null || echo '')"
interval = 2
# Clique com o botão esquerdo: Play/Pause
click-left = playerctl --player=spotify play-pause
# Scroll para mudar música
scroll-up = playerctl --player=spotify next
scroll-down = playerctl --player=spotify previous

# Option 2 (with Mpris):
;[module/spotify]
;type = custom/script
;exec = python3 ~/.config/polybar/scripts/polybar_spotify.py
;interval = 2
# Clique com o botão esquerdo: Play/Pause
;click-left = playerctl --player=spotify play-pause
# Scroll para mudar música
;scroll-up = playerctl --player=spotify next
;scroll-down = playerctl --player=spotify previous

; [module/manager-files]
; type = custom/text
; format = "  "
; ;click-left = exec pcmanfm &
; click-left = exec thunar &

; [module/browser]
; type = custom/text
; format = "  "
; click-left = exec google-chrome-stable &

; [module/editor]
; type = custom/text
; format = "  "
; click-left = exec code &

; [module/console]
; type = custom/text
; format = "  "
; click-left = exec terminator &

; [module/message]
; type = custom/text
; format = "  "
; click-left = exec qtox &

; [module/telegram]
; type = custom/text
; format = "  "
; click-left = exec telegram-desktop &

;[module/menu]
;type = custom/text
;format = "   "
;click-left = exec rofi -show drun &

;[module/battery]
;type = internal/battery
;full-at = 99
# Use the following command to list batteries and adapters:
# $ ls -1 /sys/class/power_supply/
;battery =
;adapter =
;poll-interval = 5

;[module/filesystem]
;type = internal/fs
;mount-0 = /home
;;mount-1 = /
;interval = 30
;fixed-values = false
;spacing = 1
;format-mounted = <label-mounted>
;format-unmounted = <label-unmounted>
;;label-mounted = %mountpoint%: %free% of %total%
;label-mounted = %mountpoint%: %free%

;[module/wlan]
;type = internal/network
;interface = wlp7s0
;interval = 3.0
;format-connected = <ramp-signal> <label-connected>
;format-connected = <ramp-signal>
;format-connected-foreground = #ffffff
;format-connected-background = #1d1f21
;format-connected-padding = 1
;label-connected = %essid%
;format-disconnected =
;ramp-signal-0 = 
;ramp-signal-1 = 
;ramp-signal-2 = 
;ramp-signal-3 = 
;ramp-signal-4 = 
;ramp-signal-foreground = #ffffff

;[module/network-networkmanager]
;; Font: https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/network-networkmanager
;type = custom/script
;interval = 5
;exec = ~/.config/polybar/scripts/network_networkmanager.sh
;tail = true
;;click-left = exec terminator --command="nmcli connection show | less" &
;;click-left = exec gnome-control-center network &
;click-left = exec nm-connection-editor &

## Comands:
# Disconnect: sudo networkctl down eno1
# Reconect: sudo networkctl up eno1
# Status: networctl status eno1
;[module/wan]
;type = internal/network
;interface = eno1
;interval = 3.0
;format-connected-padding = 2
;format-connected-foreground = ${colors.primary}
;format-connected-background = ${colors.secondary}
;format-connected-prefix = " "
;label-connected = %local_ip%
;format-disconnected =

;[module/notification-github]
;type = custom/script
;exec = ~/.config/polybar/scripts/notifications_github.sh
;interval = 60

[settings]
screenchange-reload = true

[global/wm]
margin-top = 0
margin-bottom = 0
