[runtime]
items-level-zero-order=1b6e48e9-b2c2-4502-87df-09376533779c;e3fe97c0-76dc-4fab-a341-fe897140d337;8c63c5ee-3fbe-4e25-8444-8ae897e6e5aa;2102c3a9-fc3c-457b-8a50-83922bff4acc;9dadda70-c79c-4962-9bc4-57eceaa04520;
items-list-order-mode=ManualOrder

items-create-root-menu=false
items-add-about-item=false
terminal-pattern=
desktop-environment=

[fma-config-tool]
main-toolbar-file-display=true
main-toolbar-edit-display=true
main-toolbar-help-display=true
main-tabs-pos=Top
main-paned-width=200
main-window-wsp=410;213;1030;560;
preferences-wsp=334;361;1068;371;
command-working-dir-chooser-lfu=file:///home/wcanin
command-working-dir-chooser-wsp=46;27;1203;936;
export-assistant-lfu=file:///home/.dotfiles/user/dotctrl/Documentos/2-filemanager-actions_exports
export-assistant-paned-width=200
export-assistant-wsp=566;341;842;316;
relabel-when-duplicate-menu=false
relabel-when-duplicate-action=false
relabel-when-duplicate-profile=false
assistant-esc-quit=true
assistant-esc-confirm=true
main-save-auto=false
main-save-period=5
import-preferred-mode=Ask
export-preferred-format=GConfSchemaV1
scheme-default-list=dav|Arquivos WebDAV;file|Arquivos locais;ftp|Arquivos FTP;sftp|Arquivos SSH;smb|Arquivos Windows;
io-providers-write-order=io-desktop;
export-ask-user-wsp=622;429;515;232;

[io-provider io-desktop]
readable=true
writable=true
